In [1]:
import torch 
import torch.nn as nn
import torch.optim as optim

### Basic Neural Network using PyTorch


###### X --> Input

###### Wx --> Weights

###### b --> Bias

###### Y --> Output

###### A --> Activation Function (Sigmoid,ReLU,Tanh)

###### Z = WX + b

###### Z` = Activation(Z)

###### Y = W2.Z` + b2


- Loss Function: MSE, Cross Entropy
- Backpropagation: Gradient Descent, Adam, RMSProp
- Optimizer: SGD, Adam, RMSProp
 


### Components of Pytorch

- Base class for defining cutom models is `torch.nn.Module`
- Layers are defined in `__init__` method
- Forward pass is defined in `forward` method
- Loss functions are defined in `torch.nn` module
- Optimizers are defined in `torch.optim` module
- Data loading and preprocessing is done using `torch.utils.data` module
- Fully connected layer is defined using `torch.nn.Linear`
- Activation functions are defined in `torch.nn.ReLU` module 
- Optimizers are defined in `torch.optim` module
- Loss functions are defined in `torch.nn.CrossEntropyLoss` module
- Loads data in batches using `torch.utils.data.DataLoader` module


### Different ways to define a model in Pytorch

1. Functional: Flexable, harder to interpret
2. Sequential: Easy to interpret, less flexable
3. Custom: Most flexable, harder to interpret

### Functional API

In [2]:
class SimpleNN(nn.Module):
   def __init__(self,input_size,hidden_size,output_size):
      super(SimpleNN,self).__init__()
       
      self.fullyConnectedLayer_1 = nn.Linear(input_size,hidden_size)
      self.relu = nn.ReLU()
      self.fullyConnnectedLayer_2 = nn.Linear(hidden_size,output_size)
       
       
   def forward(self,x):
      x = self.fullyConnectedLayer_1(x)
      x = self.relu(x)
      x = self.fullyConnnectedLayer_2(x)
      return x

### Sequential API


In [3]:
class SimpleNNSequential(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()

        self.network = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, output_size)
        )

    def forward(self, x):
        return self.network(x)

### Training the neural network using Functional API


In [4]:
model_func = SimpleNN(input_size=4, hidden_size=8,output_size=3)
print(model_func)

SimpleNN(
  (fullyConnectedLayer_1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fullyConnnectedLayer_2): Linear(in_features=8, out_features=3, bias=True)
)


In [5]:
X = torch.randn(10,4) # 10 samples, 4 features
Y = torch.randint(0,3,(10,))

print(X)
print(Y)

tensor([[ 1.1078e-02,  7.1471e-01, -2.9741e-01,  1.0817e-01],
        [-7.0193e-01, -1.5220e+00,  5.2227e-01,  2.0043e-01],
        [ 2.7192e+00, -1.1287e+00, -9.6982e-01,  9.9883e-01],
        [-2.0749e-01,  1.0156e-03, -9.5886e-01,  6.5245e-01],
        [-2.0277e-01, -1.7470e-02, -6.4231e-01, -7.9846e-01],
        [-8.2634e-01,  8.4686e-01, -4.1232e-01, -2.4988e-01],
        [-5.1659e-01,  1.4309e+00,  7.0469e-01,  6.1677e-01],
        [ 2.4391e-01,  5.5396e-01,  5.6156e-01, -1.4503e+00],
        [ 7.8056e-01, -2.9445e-02, -9.5471e-02, -1.5726e+00],
        [ 8.0370e-02,  2.0079e+00,  2.9171e-01,  1.9636e-01]])
tensor([1, 2, 0, 1, 1, 1, 2, 2, 0, 1])


In [6]:
criterion = nn.CrossEntropyLoss() # includes the advance version of sigmax function
optimizer = optim.Adam(model_func.parameters(),lr=0.01)

In [7]:
# Training Loop
epoch = 300
for e in range(epoch):
   optimizer.zero_grad() # Clear all the gradients
   outputs = model_func(X) # Passing inputs
   loss = criterion(outputs,Y)
   loss.backward()
   optimizer.step()
   
   if(e+1) % 10 == 0:
      print(f"Epoch [{e+1}]/{epoch} , Loss : {loss.item() :.4f}")
   

Epoch [10]/300 , Loss : 0.9285
Epoch [20]/300 , Loss : 0.7490
Epoch [30]/300 , Loss : 0.5819
Epoch [40]/300 , Loss : 0.4421
Epoch [50]/300 , Loss : 0.3183
Epoch [60]/300 , Loss : 0.2122
Epoch [70]/300 , Loss : 0.1375
Epoch [80]/300 , Loss : 0.0864
Epoch [90]/300 , Loss : 0.0560
Epoch [100]/300 , Loss : 0.0385
Epoch [110]/300 , Loss : 0.0284
Epoch [120]/300 , Loss : 0.0220
Epoch [130]/300 , Loss : 0.0177
Epoch [140]/300 , Loss : 0.0146
Epoch [150]/300 , Loss : 0.0124
Epoch [160]/300 , Loss : 0.0106
Epoch [170]/300 , Loss : 0.0093
Epoch [180]/300 , Loss : 0.0082
Epoch [190]/300 , Loss : 0.0073
Epoch [200]/300 , Loss : 0.0065
Epoch [210]/300 , Loss : 0.0059
Epoch [220]/300 , Loss : 0.0054
Epoch [230]/300 , Loss : 0.0049
Epoch [240]/300 , Loss : 0.0045
Epoch [250]/300 , Loss : 0.0041
Epoch [260]/300 , Loss : 0.0038
Epoch [270]/300 , Loss : 0.0035
Epoch [280]/300 , Loss : 0.0033
Epoch [290]/300 , Loss : 0.0031
Epoch [300]/300 , Loss : 0.0029


#### <b><U>Linear Regression Model using Pytorch Components
 </U> </b>

1. Data gathering
2. Data preprocessing
3. Feature engineering
4. Model training
5. Testing



In [8]:
!pip install kagglehub


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip


In [6]:
import kagglehub
import os
import shutil

# Download dataset (cached location by kagglehub)
path = kagglehub.dataset_download("mirichoi0218/insurance")
print(f"Downloaded dataset path: {path}")

# Define your custom target directory
target_dir = "./data/insurance"

# Make sure the directory exists
os.makedirs(target_dir, exist_ok=True)

# Copy all files from kagglehub cache to your custom directory
for file_name in os.listdir(path):
    src = os.path.join(path, file_name)
    dst = os.path.join(target_dir, file_name)
    shutil.copy2(src, dst)  # copy2 preserves metadata

print(f"Dataset copied to: {target_dir}")

/opt/conda/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Downloaded dataset path: /home/codespace/.cache/kagglehub/datasets/mirichoi0218/insurance/versions/1
Dataset copied to: ./data/insurance


In [7]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [8]:
df = pd.read_csv('./data/insurance/insurance.csv')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [13]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [10]:
# Split dataset before encoding
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
print(train_df.head())

      age     sex    bmi  children smoker     region      charges
560    46  female  19.95         2     no  northwest   9193.83850
1285   47  female  24.32         0     no  northeast   8534.67180
1142   52  female  24.86         0     no  southeast  27117.99378
969    39  female  34.32         5     no  southeast   8596.82780
486    54  female  21.47         3     no  northwest  12475.35130


In [11]:
# Encode cetagorical variable
label_encoder = {}
for col in ["sex", "smoker", "region"]:
    le = LabelEncoder()
    train_df[col] = le.fit_transform(train_df[col])
    test_df[col] = le.transform(test_df[col])
    label_encoder[col] = le
    print(f"Classes for {col}: {le.classes_}")

print("Final label_encoder keys:", label_encoder.values())
print(train_df.head())

Classes for sex: ['female' 'male']
Classes for smoker: ['no' 'yes']
Classes for region: ['northeast' 'northwest' 'southeast' 'southwest']
Final label_encoder keys: dict_values([LabelEncoder(), LabelEncoder(), LabelEncoder()])
      age  sex    bmi  children  smoker  region      charges
560    46    0  19.95         2       0       1   9193.83850
1285   47    0  24.32         0       0       0   8534.67180
1142   52    0  24.86         0       0       2  27117.99378
969    39    0  34.32         5       0       2   8596.82780
486    54    0  21.47         3       0       1  12475.35130


In [12]:
# Features and target
X_train = train_df.drop(columns=["charges"]) # Here we have excluded the charges column
y_train = train_df["charges"]

X_test = test_df.drop(columns=["charges"])
y_test = test_df["charges"]

In [17]:
print("X_train :\n",X_train.head())
print("y_train :\n",y_train.head())
print(y_train.values)

X_train :
       age  sex    bmi  children  smoker  region
560    46    0  19.95         2       0       1
1285   47    0  24.32         0       0       0
1142   52    0  24.86         0       0       2
969    39    0  34.32         5       0       2
486    54    0  21.47         3       0       1
y_train :
 560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
Name: charges, dtype: float64
[ 9193.8385   8534.6718  27117.99378 ... 11931.12525 46113.511
 10214.636  ]


In [13]:
# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
print(X_train)

[[ 0.47222651 -1.0246016  -1.75652513  0.73433626 -0.50874702 -0.45611589]
 [ 0.54331294 -1.0246016  -1.03308239 -0.91119211 -0.50874702 -1.35325561]
 [ 0.8987451  -1.0246016  -0.94368672 -0.91119211 -0.50874702  0.44102382]
 ...
 [ 1.3252637   0.97598911 -0.89153925 -0.91119211 -0.50874702 -1.35325561]
 [-0.16755139 -1.0246016   2.82086429  0.73433626  1.96561348  1.33816354]
 [ 1.1120044   0.97598911 -0.10932713 -0.91119211 -0.50874702  1.33816354]]


In [14]:
# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [21]:
print(y_train_tensor)
print(y_train_tensor.shape)

tensor([[ 9193.8389],
        [ 8534.6719],
        [27117.9941],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])
torch.Size([1070, 1])


In [22]:
print(X_test_tensor)
print(X_test_tensor.shape)

tensor([[ 0.4011, -1.0246, -0.8915,  0.7343, -0.5087, -1.3533],
        [-0.2386, -1.0246, -0.0895, -0.9112, -0.5087, -0.4561],
        [ 1.7518, -1.0246, -0.6085, -0.9112,  1.9656, -0.4561],
        ...,
        [-0.0965,  0.9760, -0.4197, -0.0884, -0.5087, -1.3533],
        [ 1.0409, -1.0246,  2.7894, -0.9112,  1.9656,  0.4410],
        [ 0.8277, -1.0246,  0.6025, -0.0884, -0.5087,  1.3382]])
torch.Size([268, 6])


In [24]:
# Define Neural network model


class SimpleNNRegressionModel(nn.Module):
    def __init__(self, input_dim):
        super(SimpleNNRegressionModel, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
        )

    def forward(self, x):
        return self.network(x)

In [24]:
X_train_tensor.shape

torch.Size([1070, 6])

In [25]:
input_dim = X_train_tensor.shape[1]
model = SimpleNNRegressionModel(input_dim)

In [26]:
print(model)

SimpleNNRegressionModel(
  (network): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)


In [27]:
# Loss and optmiser

criterion = nn.MSELoss()
optimiser = optim.Adam(model.parameters(), lr=0.01)

In [28]:
# Training loop
epochs = 30000

for epoch in range(epochs):
    model.train()
    optimiser.zero_grad()
    predictions = model(X_train_tensor)
    loss = criterion(predictions, y_train_tensor)
    loss.backward()

    optimiser.step()

    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss : {loss.item():.4f}")

Epoch [100/30000], Loss : 45442196.0000
Epoch [200/30000], Loss : 31621372.0000


Epoch [300/30000], Loss : 28928400.0000
Epoch [400/30000], Loss : 27083222.0000
Epoch [500/30000], Loss : 26010146.0000
Epoch [600/30000], Loss : 25244390.0000
Epoch [700/30000], Loss : 24601858.0000
Epoch [800/30000], Loss : 24110354.0000
Epoch [900/30000], Loss : 23748598.0000
Epoch [1000/30000], Loss : 23458052.0000
Epoch [1100/30000], Loss : 23227280.0000
Epoch [1200/30000], Loss : 22999318.0000
Epoch [1300/30000], Loss : 22795648.0000
Epoch [1400/30000], Loss : 22596582.0000
Epoch [1500/30000], Loss : 22412480.0000
Epoch [1600/30000], Loss : 22156996.0000
Epoch [1700/30000], Loss : 21945278.0000
Epoch [1800/30000], Loss : 21756192.0000
Epoch [1900/30000], Loss : 21586256.0000
Epoch [2000/30000], Loss : 21383810.0000
Epoch [2100/30000], Loss : 21012632.0000
Epoch [2200/30000], Loss : 20480908.0000
Epoch [2300/30000], Loss : 19696538.0000
Epoch [2400/30000], Loss : 18976982.0000
Epoch [2500/30000], Loss : 18401600.0000
Epoch [2600/30000], Loss : 17993406.0000
Epoch [2700/30000], Los

In [29]:
# Model Evaluation

model.eval()
y_pred = model(X_test_tensor).detach().numpy()

In [30]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

y_test_numpy = y_test_tensor.numpy()

# Calculate metrics
mse = mean_squared_error(y_test_numpy, y_pred)
rmse = mse**0.5
mae = mean_absolute_error(y_test_numpy, y_pred)
r2 = r2_score(y_test_numpy, y_pred)

print(f"MSE : {mse}")
print(f"RMSE : {rmse}")
print(f"MAE : {mae}")
print(f"R2-Score : {r2}")

# 0 --> 0

MSE : 50296648.0
RMSE : 7092.012972351362
MAE : 4935.44580078125
R2-Score : 0.676025390625


In [31]:
def predict_charges(age, sex, bmi, children, smoker, region):
    input_data = pd.DataFrame(
        [[age, sex, bmi, children, smoker, region]],
        columns=["age", "sex", "bmi", "children", "smoker", "region"],
    )

    for col in ["sex", "smoker", "region"]:
        input_data[col] = label_encoder[col].transform(input_data[col])
    input_data = scaler.transform(input_data)
    input_tensor = torch.tensor(input_data, dtype=torch.float32)
    predicted_charge = model(input_tensor).item()
    return predicted_charge

In [32]:
predicted = predict_charges(50, "female", 27.9, 0, "yes", "southwest")
print(f"Predicted insurance charge: ${predicted:.2f}")

Predicted insurance charge: $39509.46


### <b><U>Multi_Class Classification using Custom Neural Network</U> </b>

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [20]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["target"] = iris.target

In [40]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [22]:
train_df, test_df = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df["target"]
)

In [23]:
X_train, y_train = train_df.drop(columns=["target"]), train_df["target"]
X_test, y_test = test_df.drop(columns=["target"]), test_df["target"]
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

In [24]:
class IrisClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(IrisClassifier, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )

    def forward(self, x):
        return self.network(x)

In [25]:
input_dim = X_train.shape[1]
hidden_dim = 16
output_dim = 3

In [26]:
model = IrisClassifier(input_dim, hidden_dim, output_dim)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [32]:
# Train the model

epochs = 500
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()

    predictions = model(X_train_tensor)
    loss = criterion(predictions, y_train_tensor)

    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], loss : {loss.item():.4f}")

Epoch [10/500], loss : 0.4838
Epoch [20/500], loss : 0.2030
Epoch [30/500], loss : 0.0853
Epoch [40/500], loss : 0.0503
Epoch [50/500], loss : 0.0388
Epoch [60/500], loss : 0.0333
Epoch [70/500], loss : 0.0300
Epoch [80/500], loss : 0.0275
Epoch [90/500], loss : 0.0251
Epoch [100/500], loss : 0.0227
Epoch [110/500], loss : 0.0204
Epoch [120/500], loss : 0.0182
Epoch [130/500], loss : 0.0158
Epoch [140/500], loss : 0.0135
Epoch [150/500], loss : 0.0114
Epoch [160/500], loss : 0.0096
Epoch [170/500], loss : 0.0080
Epoch [180/500], loss : 0.0067
Epoch [190/500], loss : 0.0057
Epoch [200/500], loss : 0.0048
Epoch [210/500], loss : 0.0041
Epoch [220/500], loss : 0.0036
Epoch [230/500], loss : 0.0031
Epoch [240/500], loss : 0.0027
Epoch [250/500], loss : 0.0024
Epoch [260/500], loss : 0.0022
Epoch [270/500], loss : 0.0019
Epoch [280/500], loss : 0.0018
Epoch [290/500], loss : 0.0016
Epoch [300/500], loss : 0.0014
Epoch [310/500], loss : 0.0013
Epoch [320/500], loss : 0.0012
Epoch [330/500], 

In [ ]:
model.eval()
with torch.no_grad():
    y_pred = model(X_test_tensor) 
    y_pred_labels = torch.argmax(y_pred, dim=1)

    accuracy = (y_pred_labels == y_test_tensor).sum().item() / y_test_tensor.size(0)
    print(f"Test accuracy : {accuracy:.4f}")

Test accuracy : 0.9667


In [34]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [42]:
def predict_iris(sepal_length, sepal_width, petal_length, petal_width):
    input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    input_data = scaler.transform(input_data)
    input_tensor = torch.tensor(input_data, dtype=torch.float32)

    model.eval()
    with torch.no_grad():
        prediction = model(input_tensor)
        predicted_class = torch.argmax(prediction, dim=1).item()
    return iris.target_names[predicted_class]

In [43]:
predicted_class = predict_iris(607, 3.0, 5.4, 0.8)
print(f"Predicted species : {predicted_class}")

Predicted species : virginica


/home/codespace/.local/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


### Understanding Components of a Custom DataLoader in PyTorch


x_train_tensor = 1000000 (suppose data has over a million rows which is 10GB of data )--> 10gb OOM - out of memory

1000000 --> weight and bias, would be very large, so we need to break the data into batches, and feed the data in batches

suppose we have 1000 rows, and we want to feed the data in batches of 100 rows, so we will have 10 batches

batch_size = 100
num_batches = 1000/100 = 10 batches
num_epochs = 100
num_iterations = num_batches * num_epochs = 10 * 100 = 1000 iterations


1. Dataset (torch.utils.data.Dataset)
2. DataLoader (torch.utils.data.DataLoader)

 init() - initialised the dataset, loads data, applied preprocessing

 len() - return the total numbers of samples in the dataset
 
 getitem() - Defines how to retrieve a single data sample when an index is provide

In [15]:
from torch.utils.data import Dataset, DataLoader

In [29]:
df = pd.read_csv("./data/insurance/insurance.csv")

In [30]:
# Split dataset before encoding
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

In [31]:
# Encode categorical variables
label_encoders = {}
for col in ["sex", "smoker", "region"]:
    le = LabelEncoder()
    train_df[col] = le.fit_transform(train_df[col])
    test_df[col] = le.transform(test_df[col])
    label_encoders[col] = le  # Store encoders for later use

In [32]:
# Features and target
X_train = train_df.drop(columns=["charges"])
y_train = train_df["charges"]
X_test = test_df.drop(columns=["charges"])
y_test = test_df["charges"]

In [34]:
# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)

(1070, 6)


In [35]:
# Define Neural Network Model
class SimpleNNRegressionModel(nn.Module):
    def __init__(self, input_dim):
        super(SimpleNNRegressionModel, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
        )

    def forward(self, x):
        return self.network(x)

# Initialize model
input_dim = X_train.shape[1]
model = SimpleNNRegressionModel(input_dim)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [36]:
class InsuranceDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        features = torch.tensor(self.X[idx], dtype=torch.float32)
        target = torch.tensor(self.y.values[idx], dtype=torch.float32)
        return features, target

In [37]:
dataset = InsuranceDataset(X_train, y_train)

In [38]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True, num_workers=4)

In [39]:
for batch_idx, (features, targets) in enumerate(dataloader):
    print(f"Batch {batch_idx+1} :")
    print("Features : ", features.shape)
    print("Targets : ", targets.shape)
    break

Batch 1 :
Features :  torch.Size([32, 6])
Targets :  torch.Size([32])


In [41]:
epochs = 1000
for epoch in range(epochs):
    model.train()

    for batch_idx, (batch_X, batch_y) in enumerate(dataloader):
        print(f"Current batch : {batch_idx}")
        optimizer.zero_grad()
        predictions = model(batch_X)
        loss = criterion(predictions, batch_y)
        loss.backward()
        optimizer.step()
        print(f"Batch [{batch_idx+1}/{epochs}], Loss: {loss.item():.4f}")

    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Current batch : 0
Batch [1/1000], Loss: 144845312.0000
Current batch : 1
Batch [2/1000], Loss: 132247296.0000
Current batch : 2
Batch [3/1000], Loss: 171029568.0000
Current batch : 3
Batch [4/1000], Loss: 128426976.0000
Current batch : 4
Batch [5/1000], Loss: 293272960.0000
Current batch : 5
Batch [6/1000], Loss: 225138656.0000
Current batch : 6
Batch [7/1000], Loss: 226777216.0000
Current batch : 7
Batch [8/1000], Loss: 117919328.0000
Current batch : 8
Batch [9/1000], Loss: 66900460.0000
Current batch : 9
Batch [10/1000], Loss: 125864720.0000
Current batch : 10
Batch [11/1000], Loss: 205878224.0000
Current batch : 11
Batch [12/1000], Loss: 158170592.0000
Current batch : 12
Batch [13/1000], Loss: 133049784.0000
Current batch : 13
Batch [14/1000], Loss: 79004832.0000
Current batch : 14
Batch [15/1000], Loss: 109173160.0000
Current batch : 15
Batch [16/1000], Loss: 77186136.0000
Current batch : 16
Batch [17/1000], Loss: 164614176.0000
Current batch : 17
Batch [18/1000], Loss: 180356304.0

KeyboardInterrupt: 