In [1]:
import torch

In [2]:
# 1. Scalar Tensor

scalar = torch.tensor(42)

print("scalar Tensor :", scalar)
print("scalar Dimension :", scalar.ndim)
print("scalar Shape :", scalar.shape)


scalar Tensor : tensor(42)
scalar Dimension : 0
scalar Shape : torch.Size([])


In [3]:
# 1D Vector
vector = torch.tensor([1,3,3,4,5,5])

print("vector Tensor :", vector)
print("vector Dimension :", vector.ndim)
print("vector Shape :", vector.shape)
print("data Type of matrix : ", vector.dtype)

vector Tensor : tensor([1, 3, 3, 4, 5, 5])
vector Dimension : 1
vector Shape : torch.Size([6])
data Type of matrix :  torch.int64


In [4]:
# 2D Matrix
matrix_2d = torch.tensor([[1,5,5],[3,3,4]])

print("matrix_2d Tensor :", matrix_2d)
print("matrix_2d Dimension :", matrix_2d.ndim)
print("matrix_2d Shape :", matrix_2d.shape)
print("data Type of matrix : ", matrix_2d.dtype)
print("Number of elements :", matrix_2d.numel())

matrix_2d Tensor : tensor([[1, 5, 5],
        [3, 3, 4]])
matrix_2d Dimension : 2
matrix_2d Shape : torch.Size([2, 3])
data Type of matrix :  torch.int64
Number of elements : 6


In [5]:
# Tensor

tensor = torch.tensor([
       [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
       ])
print('Tensor :', tensor)
print('Tensor Dimension :' , tensor.ndim)
print('Tensor Shape : ', tensor.shape)
print("data Type of matrix : ", tensor.dtype)
print('Number of elements :', tensor.numel())

Tensor : tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])
Tensor Dimension : 3
Tensor Shape :  torch.Size([1, 3, 3])
data Type of matrix :  torch.int64
Number of elements : 9


In [6]:
# For GPU Acceleration

if torch.cuda.is_available():
   gpu_tensor = vector.to('cuda')
   print("Tensor on GPU: ", gpu_tensor)
else:
   print("CUDA is not available on this machine")

CUDA is not available on this machine


In [7]:
# Check to see the device its running on

print("Device", matrix_2d.device)

Device cpu


In [8]:
import platform
import os

print("Processor:", platform.processor())
print("Machine:", platform.machine())
print("System:", platform.system())
print("CPU count:", os.cpu_count())

Processor: x86_64
Machine: x86_64
System: Linux
CPU count: 2


In [9]:
import os, psutil

print("CPU cores:", os.cpu_count())
print("RAM (GB):", round(psutil.virtual_memory().total / 1e9, 2))

CPU cores: 2
RAM (GB): 8.33


In [10]:
# If nvidia is being used then

# !nvidia-smi

In [ ]:
# Accessing elements in a tensor
tensor = torch.tensor([[10,30,33],[40,50,65],[23,54,54]])

print(tensor.ndim)
# Element by position
print(tensor[0,2])
# Row
print(tensor[0])
# Coloumn
print(tensor[:,0])

2
tensor(33)
tensor([10, 30, 33])
tensor([10, 40, 23])


In [48]:
# Slicing
print(tensor)
print("first two rows: \n", tensor[:2])
print("first two coloumns : \n", tensor[:,:2])
# To access [50,60]
print(tensor[1,1:]) # tensor[1,1:3]
# accessing random elements that are not in order ie accessing (40,54)
print(tensor[[1,2],[0,2]])
# Boolean indexing
mask = tensor > 50
print(mask)
print(tensor[mask])
# Changing tensor values via Index position
tensor[0,1] = 500
# Changing tensor colums or rows via Index position
tensor[:,0] = torch.tensor([100,200,300])

print(tensor)

tensor([[100, 500,  33],
        [100,  50,  65],
        [100,  54,  54]])
first two rows: 
 tensor([[100, 500,  33],
        [100,  50,  65]])
first two coloumns : 
 tensor([[100, 500],
        [100,  50],
        [100,  54]])
tensor([50, 65])
tensor([100,  54])
tensor([[ True,  True, False],
        [ True, False,  True],
        [ True,  True,  True]])
tensor([100, 500, 100,  65, 100,  54,  54])
tensor([[100, 500,  33],
        [200,  50,  65],
        [300,  54,  54]])


In [49]:
indices = torch.tensor([0,2])
# dim = 0 mean rows and dim = 1 equals columns
selected_rows = torch.index_select(tensor,dim=0,index = indices)
print(selected_rows)

tensor([[100, 500,  33],
        [300,  54,  54]])


In [56]:
# Fliping rows and columns
torch.flip(tensor,[0,])

tensor([[300,  54,  54],
        [200,  50,  65],
        [100, 500,  33]])